package classes;

public enum Type {
    RESERVED_KEYWORD,
    IDENTIFIER,
    INTEGER_NUMBER,
    REAL_NUMBER,
    BOOLEAN,
    HEX,
    SCIENTIFIC_NOTATION,
    STRING,
    SPECIAL_CHAR,
    COMMENT,
    OPERATOR_AND_PUNCTUATION,
    WHITESPACE,
    UNDEFINED,
}
